name: expense_repository
description: The Repo that handles expense
publish_to: 'none'
version: 0.0.1

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # equatable: ^2.0.7
  firebase_auth: ^5.4.1
  cloud_firestore: ^5.6.2
  # firebase_storage: ^12.4.1
  rxdart: ^0.28.0
  # path: ^1.9.0
  uuid: ^4.5.1
  intl: ^0.20.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true